services:
  - type: web
    name: coin-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential gcc
      pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free
    region: oregon
